### PR TITLE
Added support for `...on` clause for Unions

### PR DESCRIPTION
**Pull request by JuanuMusic**
Implement querying for Union Types (SEE  https://graphql.org/learn/schema/#union-types)
This Includes the implementation of `AddPossibleType` on the query builder to generate `... on` clauses. Added test cases. All passing.

Nested works as expected 😀

### CODE REVIEW

**Comment by JuanuMusic** [comment]
Hi @charlesdevandiere Im still polishing some rough edges on this, but it looks like the build action is not working.
Also, do you think its interesting to add this feature?

**Comment by charlesdevandiere** [comment]
Hi @JuanuMusic, thank you for implementing union types. It looks like the test step no longer generates the same artifact. You can try replacing 'coverage.cobertura.xml' with 'coverage.json' in file https://github.com/JuanuMusic/graphql-query-builder-dotnet/blob/on_clause/azure-pipelines.yml#L42

**Comment by richardaubin** [comment]
Looking forward to having this implemented.  I just had my first use case, and had to resort to copying and pasting the query as string in my code :(

**Comment by charlesdevandiere** [comment]
Thank you very much for your contribution. I finally made my own implementation with AddUnion

**Pull request closed without merging**
